// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3mO57IIF_Yl90AlP5DnF9hHgXec12RI',
    appId: '1:228025746361:web:d00cc39ebb2e0c1b6dac68',
    messagingSenderId: '228025746361',
    projectId: 'kube-b1e94',
    authDomain: 'kube-b1e94.firebaseapp.com',
    storageBucket: 'kube-b1e94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIOpnP1Vtwl6Pn67VxhV1WLEhj6WfEWtI',
    appId: '1:228025746361:android:aced2ff942d654e76dac68',
    messagingSenderId: '228025746361',
    projectId: 'kube-b1e94',
    storageBucket: 'kube-b1e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bET577Lhih0xPWCNZBzYeJTyhn-moq8',
    appId: '1:228025746361:ios:62af59e3e6919b356dac68',
    messagingSenderId: '228025746361',
    projectId: 'kube-b1e94',
    storageBucket: 'kube-b1e94.firebasestorage.app',
    iosBundleId: 'com.example.kube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bET577Lhih0xPWCNZBzYeJTyhn-moq8',
    appId: '1:228025746361:ios:62af59e3e6919b356dac68',
    messagingSenderId: '228025746361',
    projectId: 'kube-b1e94',
    storageBucket: 'kube-b1e94.firebasestorage.app',
    iosBundleId: 'com.example.kube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo3mO57IIF_Yl90AlP5DnF9hHgXec12RI',
    appId: '1:228025746361:web:a3598de7b1c2b3e96dac68',
    messagingSenderId: '228025746361',
    projectId: 'kube-b1e94',
    authDomain: 'kube-b1e94.firebaseapp.com',
    storageBucket: 'kube-b1e94.firebasestorage.app',
  );
}
